### ISSUE TITLE
Add responsive nav bar to website

### ISSUE THREAD

**Issue by elimisteve** [PursuanceProject/website#11]
Nav link names and associated URLs:

- What is Pursuance? `#what`
- Media `#media`
- Team `#team`
- FAQ `#faq`
- Contact `#contact`
- Donate `#donate`
- Broader Vision `#vision`

**Comment by seabassgonzalez** [comment]
What would the ideal sections linked to be (e.g. about, intro, visualization, collaboration)? Named as such?

**Comment by elimisteve** [comment]
@seabassgonzalez Just updated the description here ^^

**Comment by elimisteve** [comment]
Let's move the contents of `donate.html`, excluding the big banner up top, to a section in `index.html` :+1:

**Comment by elimisteve** [comment]
Team subsections (not linked to from the top nav bar) -- https://github.com/PursuanceProject/website/issues/6#issuecomment-352948271

**Comment by elimisteve** [comment]
@seabassgonzalez Let's add these social media icons and links to the Contact section: https://github.com/PursuanceProject/website/issues/9

**Comment by elimisteve** [comment]
@seabassgonzalez Which parts of all this do you want to do and which should I help with now/today?

**Comment by seabassgonzalez** [comment]
If you want to tackle #6 and #7, organizing that content/subsections on the page as you see fit; I'll work on the bootstrapped navbar, will look for remaining images for the board members, and add buttons linking to the various social media sites
