### ISSUE TITLE
Create a Team page

### ISSUE THREAD

**Issue by elimisteve** [PursuanceProject/website#6]
URL: `/team`. File: `team.html`

Should include the people listed in https://dlf23ukayqpqu1zf3ckn.oasis.sandstorm.io/index.html?transition=none#/26

as well as the advisers and board members announced in https://motherboard.vice.com/en_us/article/gyynwm/barrett-brown-what-is-to-be-done

**Comment by elimisteve** [comment]
@ajvb Can you add the Bootswatch theme and add this page between Nov 27th and 30th?

**Comment by ajvb** [comment]
@elimisteve couple of quick questions:
1. Do we want to include pictures of people?
2. Do you mean all three slides of the sandstorm slide deck? Should we do a "Core Team" section and "Volunteers" section?

**Comment by elimisteve** [comment]
1. Yes. I'll get those now for you.

2. How about:

## Core Team

## Core Volunteers

## Board of Directors

**Comment by ajvb** [comment]
@elimisteve awesome, sounds great. Once #8 is merged I'll bust this out.

**Comment by elimisteve** [comment]
@ajvb I've solicited photos for the Team page; should have them soon.

**Comment by elimisteve** [comment]
Team pics: https://keybase.pub/pursuance/images/team/

**Comment by seabassgonzalez** [comment]
Would it be ideal to include images for the board members listed in the motherboard article as well?

**Comment by elimisteve** [comment]
@seabassgonzalez Yes, and you can get some of those images from https://keybase.pub/pursuance/images/team/
