### ISSUE TITLE
Add social media icons or similar

### ISSUE THREAD

**Issue by ajvb** [PursuanceProject/website#9]
Twitter + Github, anything else?

**Comment by elimisteve** [comment]
LinkedIn: https://www.linkedin.com/company/18236625/

Instagram: https://www.instagram.com/pursuanceproject/

Facebook: https://www.facebook.com/PursuanceProject/

YouTube: https://www.youtube.com/channel/UCPOCibJUeuKRJT-sdc9t9Ew (looks like a URL we should change...)

**Comment by elimisteve** [comment]
See also: https://github.com/PursuanceProject/website/issues/7#issuecomment-357111096
